# Created with YamlCreate.ps1 v2.2.1 $debug=NVS1.CRLF.7-3-0.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: Tarma.PublishOrPerish
PackageVersion: 8.6.4214.8378
InstallerType: exe # InstallMate
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /q2 /b0
  SilentWithProgress: /q1 /b0
  InstallLocation: '"INSTALLDIR=<INSTALLPATH>"'
  Log: /log:"<LOGPATH>"
ExpectedReturnCodes:
- InstallerReturnCode: 5
  ReturnResponse: cancelledByUser
# - InstallerReturnCode: 9
#   ReturnResponse: invalidParameter
# - InstallerReturnCode: 11
#   ReturnResponse: systemNotSupported
- InstallerReturnCode: 12
  ReturnResponse: rebootRequiredToFinish
- InstallerReturnCode: 13
  ReturnResponse: packageInUse
- InstallerReturnCode: 14
  ReturnResponse: alreadyInstalled
- InstallerReturnCode: 16
  ReturnResponse: diskFull
- InstallerReturnCode: 20
  ReturnResponse: installInProgress
UpgradeBehavior: install
FileExtensions:
- pxa
ReleaseDate: 2022-12-08
Installers:
- Architecture: x86
  InstallerUrl: https://harzing.com/download/PoP8Setup.exe
  InstallerSha256: 3776147f8caa921dbebc486a5eef51a03ae809aa1ef27304a992cbef8a3f8fe9
  ProductCode: '{D7808C1C-93A9-4369-8385-A789888ED9D7}'
ManifestType: installer
ManifestVersion: 1.2.0
